spring.application.name=JobConnect
spring.datasource.url=jdbc:mysql://localhost:3306/jobconnectdb
spring.datasource.username=root
spring.datasource.password=mahi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
